const xlsx = require("xlsx");

const data = [
  {
    name: "אוריה גאון",
    team: "צוות 1",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 8,
    name: "אלון גנות",
    team: "צוות 1",
    phone: "0549371378",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/kacl6gunadcehuvt1ia5",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 31,
    name: "אפרת לופס",
    team: "צוות 1",
    phone: "0556676974",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/fc2qx7enfzofjctvm8rt",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "דניאל פרישצפוב",
    team: "צוות 1",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 24,
    name: "יובל תבור",
    team: "צוות 1",
    phone: "0584255041",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/xbin5coeuqii20ketlgx",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "יפתח סרור",
    team: "צוות 1",
    phone: "0504537324",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/bq1stczsfpchkbjacops",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "ירדן נזרצקי",
    team: "צוות 1",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "ניב גינגולד",
    team: "צוות 1",
    phone: "0543330290",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/ltb4nkfe7monyl4jhkxe",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "רותם יושעי",
    team: "צוות 1",
    phone: "0547475401",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/ks5qeajcz4m7iqmh13al",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 2,
    name: "אילון עמר",
    team: "צוות 2",
    phone: "0528194577",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/e38ehqcjnsqgnzpfkd7a",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 15,
    name: "אריאל עמוסי",
    team: "צוות 2",
    phone: "0545607722",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/ocjuxj71pp0l7wzufusy",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "דן יוסף ברימה",
    team: "צוות 2",
    phone: "0585979676",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/l5xxbavaz81nyl5tpw8s",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "הראל זינגר",
    team: "צוות 2",
    phone: "0542486123",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/wkljpvil95flokvu8ckb",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 33,
    name: "עידן אביעד",
    team: "צוות 2",
    phone: "0549208258",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/l3n2g9atld7nso0eiqut",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "עידן גלנט",
    team: "צוות 2",
    phone: "0558855246",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/ro5jilt9hdoqcnt2mneq",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "עמית פינקל",
    team: "צוות 2",
    phone: "0548037997",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/a8jqgqezkjialk5off5l",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "פלג מסד פורן",
    team: "צוות 2",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 28,
    name: "ראמי סרחאן",
    team: "צוות 2",
    phone: "0505889882",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/rfgcfsf9eaiuiuo5k34x",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 11,
    name: "אילן וסילבסקי",
    team: "צוות 3",
    phone: "0526223319",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/po3ub8kdvkazxvnrz2jv",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 16,
    name: "ולדימיר מורייב",
    team: "צוות 3",
    phone: "0548339094",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/bx45jmrcczgepfaz6l6e",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "חגי צגאי",
    team: "צוות 3",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 34,
    name: "ירין הרטמן",
    team: "צוות 3",
    phone: "0547241686",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/fwn5lhrhg9otlaqbdx6e",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 21,
    name: "כאמל מוראד",
    team: "צוות 3",
    phone: "0509805318",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/zjjzlh9b031dco6h8oia",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "נועה חסיד",
    team: "צוות 3",
    phone: "0524085033",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/ygzljnweai6bycufe1da",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 13,
    name: "נעה אופק",
    team: "צוות 3",
    phone: "0532442248",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/jaz6crujjkkhxeyyxcta",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 18,
    name: "עומר ברנשטיין",
    team: "צוות 3",
    phone: "0532742334",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/e8juzgcmutlln3b8ndxk",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 26,
    name: "עילי רז",
    team: "צוות 3",
    phone: "0506388128",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/ip2woioydbkbkir0fnsj",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 17,
    name: "שגב בורשטיין",
    team: "צוות 3",
    phone: "0508890639",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/xxpgll4xfrdpkvh9o4jq",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 7,
    name: "שחר דונסקי",
    team: "צוות 3",
    phone: "0527980602",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/jp4dxin7cfobbtwmisyb",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 32,
    name: "אילון בן ישי",
    team: "צוות 4",
    phone: "0546172928",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/wvt99ejc3xi9dfvxv3ua",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "ארי וייס",
    team: "צוות 4",
    phone: "",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 9,
    name: "אריאל אנגל",
    team: "צוות 4",
    phone: "0502994969",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/zx30votasze3ob3lerfz",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "הלל לוי",
    team: "צוות 4",
    phone: "0543180088",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/unsijk8muspvfptuuclr",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 5,
    name: "יובל סרוסי",
    team: "צוות 4",
    phone: "0522803670",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/t6lucowp6ajdfiypqxxx",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: true,
    absentReason: "",
  },
  {
    name: "מיכאל אטיאס",
    team: "צוות 4",
    phone: "0503927395",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/kpiorz1vofok0zgcrprf",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "נבו אוזן",
    team: "צוות 4",
    phone: "0524488999",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/okkmwwhifxh0e1xawujo",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 1,
    name: "נדב קרשין",
    team: "צוות 4",
    phone: "0546232883",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/acwcshtrvj4zg7i7c1ng",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: true,
    absentReason: "",
  },
  {
    name: "ניצן רוזנגר",
    team: "צוות 4",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "נמרוד ויין",
    team: "צוות 4",
    phone: "0546060991",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/xrdncqdjb4hfae02jt6c",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "שגיא תעיזי",
    team: "צוות 4",
    phone: "0533039456",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/phnz7emp6etayi54xnxb",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 4,
    name: "אליזה וואקי",
    team: "צוות 5",
    phone: "0587065252",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/lodrxktxebeqhinlgdae",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "הדר וינטראוב",
    team: "צוות 5",
    phone: "0542299083",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/j2jcpbhwlv3fb5b4t7oz",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 29,
    name: "הדר פקלר",
    team: "צוות 5",
    phone: "0586800156",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/i0s3pzh80b6vwiyiyhby",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "מאור אקריש",
    team: "צוות 5",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "מאיה רז",
    team: "צוות 5",
    phone: "0546306222",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/gkowe05ma2ibxeel4dvs",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 10,
    name: "רוני זוהר רוזן",
    team: "צוות 5",
    phone: "0532824440",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/mhz21nrcyawcup1y4w6b",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "רועי מאיר",
    team: "צוות 5",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 25,
    name: "אור פלורנטין",
    team: "צוות 6",
    phone: "0524757539",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/xewuemppgexdi38vkgxq",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "דן רפאל יצחקי",
    team: "צוות 6",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 23,
    name: "כרמל הודיה יהודה",
    team: "צוות 6",
    phone: "0543088604",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/s4fqfe39dtokrirxaosy",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 19,
    name: "עדי אליהו",
    team: "צוות 6",
    phone: "0524488788",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/a9fbthl3tnhns7psxeoa",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 6,
    name: "עדן קריו",
    team: "צוות 6",
    phone: "0543422089",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/fz5fuiq9kw8mcbgbyhiy",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "רועי אלישייב",
    team: "צוות 6",
    phone: "0549554717",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/szkbvn1ldnfxipwjricx",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "שירה אברהם",
    team: "צוות 6",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 27,
    name: "שני נגאר",
    team: "צוות 6",
    phone: "0524597369",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/rb6nuwpdulriy0dhsh7s",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "אורי לוטן",
    team: "צוות 7",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 3,
    name: "אמיתי כהן",
    team: "צוות 7",
    phone: "0535211014",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/xkoxxwuzm56zxr5r8226",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 35,
    name: "גיא דנינו",
    team: "צוות 7",
    phone: "0522334557",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/kura83o0ty6smakifshj",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "גיא הופמן",
    team: "צוות 7",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "גיא מנשה",
    team: "צוות 7",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "גיא רג'ואן",
    team: "צוות 7",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 20,
    name: "ערד פלד",
    team: "צוות 7",
    phone: "0528036969",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/h6pyhowbqzjxuscotkbs",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 22,
    name: "רועי מסקליק",
    team: "צוות 7",
    phone: "0523777382",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/gnv3sqklvzsweymc58vf",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "שגב הרפז",
    team: "צוות 7",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "שחר באר",
    team: "צוות 7",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 30,
    name: "אביב פינקלשטיין",
    team: "צוות 8",
    phone: "0544884282",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/ivzcxqzl3xisbwe3efzd",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "אביתר עוזרי",
    team: "צוות 8",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "אלעד בן שלוש",
    team: "צוות 8",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "בן עטרה",
    team: "צוות 8",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 14,
    name: "גדעון פרוינד",
    team: "צוות 8",
    phone: "0584593603",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/zsixoubdt2p8y0h6rndb",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "דביר דהן",
    team: "צוות 8",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    id: 12,
    name: "יהלי שחר",
    team: "צוות 8",
    phone: "0532257185",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/ilgbzyzvyccxjun4k5eq",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "ליאל בהנם",
    team: "צוות 8",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "מור עשרי",
    team: "צוות 8",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "רום סארוגטי",
    team: "צוות 8",
    phone: "",
    avatar: "",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
  {
    name: "רומן יוחננוב",
    team: "צוות 8",
    phone: "0533350841",
    avatar:
      "https://res.cloudinary.com/nadavkrashin/image/upload/f_auto,q_auto/v1/MiPo/wea2qpz1koywgv9nqetw",
    present: false,
    isHome: false,
    isMamash: false,
    isAdmin: false,
    absentReason: "",
  },
];

const filteredData = data.map(({ name, team, phone }) => ({
  name,
  team,
  phone,
}));

// Create a new workbook and a worksheet
const wb = xlsx.utils.book_new();
const ws = xlsx.utils.json_to_sheet(filteredData);

// Append the worksheet to the workbook
xlsx.utils.book_append_sheet(wb, ws, "Sheet1");

// Write the workbook to a file
xlsx.writeFile(wb, "output.xlsx");

console.log("Excel file created successfully!");
