# fly.toml app configuration file generated for mipo on 2024-05-31T20:10:11+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mipo'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
